### PR TITLE
Update master branch dependencies and associated bugfixes

### PR DESCRIPTION
**Pull request by jacobsky**
Jumped forward to gdnative 0.10.0 thanks to @bromeon 's changes in #32 I also incorporated the necessary changes to work with egui-themes.

Probably still some more minor things to wrap up before we can do a 0.2.0 release, but any additional testing that folks can do would be greatly appreciated.

Note: At the time of opening this PR, the egui-theme and egui-stylist crates have not yet been published. I'm going to do that shortly.

### CODE REVIEW

**Comment by derivator** [comment]
I've started testing this and am having some trouble with the fonts... Seems to me like partial texture updates are not working properly? I have some buttons with emojis on them, e.g. "👎" and they don't show up at all. If I display `egui_demo_lib::DemoWindows` and then show my emoji-buttons, all text suddenly becomes vertically stretched. Opening the font book fixes it, maybe because that triggers a full texture update.

Another issue: enlarging the font size in the font book causes a silent crash.

**Comment by jacobsky** [comment]
@derivator Thank you for the info. I'll see if I can't test that out.

**Comment by derivator** [comment]
@jacobsky I can confirm that the texture gets messed up on a partial update. I don't understand the existing code there, but even just getting the texture and setting it again (unchanged) messes it up: 

```rust
let delta_image = Image::new();
delta_image.create_from_data(
    delta.image.width() as _,
    delta.image.height() as _,
    false,
    Image::FORMAT_RGBA8,
    pixel_delta
);

if let Some(pos) = texture_pos {
    let old_image = texture.get_data().expect("this must exist");
    let old_image = unsafe { old_image.assume_safe() };
    let blit_rect = Rect2 { position: Vector2::ZERO, size: delta_image.get_size() };

    // this should update the texture, but we leave it out for now:
    //old_image.blit_rect(delta_image, blit_rect, Vector2::new(pos[0] as _, pos[1] as _)); 

    // the next line messes up the texture:
    texture.cast::<ImageTexture>().expect("`ImageTexture` is subclass of `Texture`").set_data(old_image);
    godot_print!("Partial update - broken")
} else {
    // this works fine:
    texture.cast::<ImageTexture>().expect("`ImageTexture` is subclass of `Texture`").set_data(delta_image);
    godot_print!("Full update - works fine")
};
```

It seems to me like `texture.get_data()` is returning faulty data?

**Comment by derivator** [comment]
> @jacobsky I can confirm that the texture gets messed up on a partial update.

I've found the issue and will submit a patch later today.

**Comment by derivator** [comment]
> @jacobsky I can confirm that the texture gets messed up on a partial update.
> Another issue: enlarging the font size in the font book causes a silent crash.

Both fixed in https://github.com/jacobsky/godot-egui/pull/2.

**Comment by jacobsky** [comment]
@derivator Thank you so much! I will get that merged in and then wrap up this PR in the next couple of days.

Sorry for the delay on this, I got caught up in other stuff.

**Pull request merged**
