### PR TITLE
Theme editor support

### PR DESCRIPTION
**Pull request by jacobsky**
This contains a large number of changes to help integrate themes into Egui as per #5 . Currently it appears to be working but is *definitely* not ready to be merged.

I wanted to submit this for feedback so that I can clean it up a bit more. Also, I think I still need to figure out how to switch which font is being used. That isn't in yet, oops.

### CODE REVIEW

**Comment by setzer22** [comment]
I like the current direction where things are going! I was able to compile your branch and play with the theme editor. I haven't had time to make an in-depth look at the code, but at a quick glance, things look fine :+1:

I don't see any huge changes to the GodotEgui's core, except for the new optional parameter with the theme. This would qualify as a breaking change, but given the way GodotEgui is intended to be used, I'd say the chance for introducing breakage with any of these changes is actually very thin.

Now, about the theme editor itself (even if this is not about godot-egui :sweat_smile:, there are a couple things:

- Something that definitely needs an improvement is the Preview tab. Making it into a separate column so you can see the theme as you are editing it should make for a much better UX.
- There was some issue with the font data when loading egui-stylist that causes a panic when trying to load serialized themes, here's my console output (in case it helps!):

       load theme
      thread '<unnamed>' panicked at 'No font data found for "DroidSansFallback"', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/epaint-0.14.0/src/text/fonts.rs:517:32
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      ERROR: <native>: gdnative-core: method panicked (check stderr for output)
         At: egui_stylist_addon/src/stylist.rs:49.
      disable input on `GodotEgui`
      on_file_dialog_closed
      reenable input on `GodotEgui`
      on_file_selected
      thread '<unnamed>' panicked at 'this should load: Error { code: Message("missing field `font_data`"), position: Position { line: 0, col: 0 } }', egui_stylist_addon/src/stylist.rs:160:30
      ERROR: <native>: gdnative-core: method panicked (check stderr for output)
         At: egui_stylist_addon/src/stylist.rs:69.

**Comment by jacobsky** [comment]
Thank you for the feedback! I'll take a closer look at the font serialization stuff. I wonder if I have the proper themes in check.

One point that I wanted to check, should we keep the `custom_fonts` and `override_custom_fonts` included in this? Perhaps it may make more sense to move the fields in favor of an optional `override_monospace_font` and `override_proportional_font` since the themes should be doing that by themselves.

I'll take another look at the panic.

I also definitely agree with making the preview a second panel. I'll look into switching that around soon(tm) 😆

**Comment by jacobsky** [comment]
I was able to reproduce the panic. It looks like I missed the fact that the font data wasn't being serialized and forgot that when extracting the theme, you also need to extract the serialized font data.

I've pushed an update to the egui-stylist repo and I'll work on testing this one.

**Comment by jacobsky** [comment]
After some quick testing, it looks like there are no longer any issues with loading the `FontData` from the `EguiTheme` so it's working.

I have a couple of questions where I'd like your opinion going forward.

Should we keep the Custom fonts info, since that gets embedded into the theme it's a smidge redundant now, so I was wondering if we should go ahead and remove them?

Also, do you have any ideas on how to write a custom importer?

 One problem that I've found is that exporting the theme as a .tres using the addon will create an `GodotEguiTheme` that is potentially pointing at the wrong library. As this is the case, I think that it might be best to have the addon only export as a `.ron` or `.eguitheme` and then write a custom resource importer that can be used to turn that file into a .tres which can be used in Godot.

I think once those are in place, I can get this PR ready for review properly :)

**Comment by jacobsky** [comment]
@setzer22 I finished up fixing up some additional bugs and writing the theme importer into Godot, this fixes a few other issues related to native_scripts not really working between projects.

I just have the last question about what to do about the customizations already present in `GodotEgui` (namely the custom  fonts) and once we come to a consensus on whether it's fine as is, or if we should remove them, I think this PR will be ready for review.

**Comment by jacobsky** [comment]
Looks like there's also some conflicts, so feel free to let me know what you'd like to approach those changes.

**Comment by setzer22** [comment]
> Looks like there's also some conflicts, so feel free to let me know what you'd like to approach those changes.

About the conflicts. I see no conflict on Cargo.toml :thinking:, we should be fine by taking your version (which only adds dependencies and doesn't delete any).

Cargo.lock is a bit weird. Should we be even versioning Cargo.lock in a library? I don't think so :sweat_smile:. I will remove this in a later commit. For now just feel free to push your changes to the file.

Now, the changes on `lib.rs` _are_ important. There was a bug on the PR that fixed the clippy lints where `len() > 0` was replaced with `is_empty()`. The only addition (and the conflicting one) was just adding that `!` operator in front so we check for non-empty instead. Whatever changes you introduced there, you should make sure the ! is added.

As we discussed, the Custom Font code won't be there for long, but it's still a good idea to keep it around until the theme editor is a bit more battle-tested, so as to not break any projects relying on it without a solid alternative just yet.

**Comment by jacobsky** [comment]
@setzer22 Ah, I already deleted the custom font code. We can revert that if needed.

**Comment by setzer22** [comment]
> @setzer22 Ah, I already deleted the custom font code. We can revert that if needed.

No need! We just need to make sure the new custom font setup works before merging :+1: 

I also noticed another minor issue: The dylib is not automatically copied to `res://addons/egui_stylist/`, but Godot expects it to be there. There's two ways we can approach this, either we automate it so building the project copies the library files there, or we make Godot's `.gdnlib` file reference its parent folder (just like it's done in `example_project`).

I think the latter approach is simpler, you just need to adapt the files with a text editor (godot won't let you go above res:// on the UI, but has no trouble doing so if the path is correct)

**Comment by jacobsky** [comment]
I updated the readme as you mentioned in the discord.

> I also noticed another minor issue: The dylib is not automatically copied to `res://addons/egui_stylist/`, but Godot expects it to be there. There's two ways we can approach this, either we automate it so building the project copies the library files there, or we make Godot's `.gdnlib` file reference its parent folder (just like it's done in `example_project`).
> 
> I think the latter approach is simpler, you just need to adapt the files with a text editor (godot won't let you go above res:// on the UI, but has no trouble doing so if the path is correct)

As this is intended to be an addon, I have some minor reservations to assuming how someone is building their code (such as where the binary is located). The reason being that some people like to include their source directory in the project folder, while others like myself may prefer keeping the rust files outside of the project directory. Especially as it is not an example intended for immediate consumption, but instead an addon that should be configured separately, I think the instructions I added to the addons should be sufficient for now.

I do agree, I would like to figure out if there is a better way to help distribute the addons. Especially since they aren't available from crates.io

**Pull request merged**
