### PR TITLE
Color test

### PR DESCRIPTION
**Pull request by jacobsky**
This is the first steps towards resolving #14
I would like to give a chance for folks to give this a test for feedback before I finalize the PR. Any observations based on the color would be greatly appreciated. Also if there's a solution for the current blending issue, any advice would be welcome.

### CODE REVIEW

**Comment by jacobsky** [comment]
While not perfect, the color tests are now mostly passing and the code is using the correct code paths for srgb data. This should help more of the GUIs retain the expected color of egui.

@setzer22 let me know what you think of these changes and then I can handle the swashing and merging into trunk.

I also am attempting to add some CI checks to this, while not all will be passing, hopefully we can at least use this to gauge the health of the project.

**Comment by jacobsky** [comment]
This issue resolves #14

**Comment by jacobsky** [comment]
As mentioned via discord, I am merging this

**Comment by setzer22** [comment]
I don't know if I did something wrong on my end, but it looks like all of my colors broke badly after merging this. See pic for reference:

image

Will need to revert this locally for the time being, since I don't have a lot of time to investigate this further.

**Pull request merged**
